spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tDszjeKJt6L7qhnSVSZ
      secret-key: 2d6trliehgKdh1JQOiTrE6DAKewsGE
      oss:
        endpoint: oss-us-west-1.aliyuncs.com
        bucket: gulimall-seattle
  application:
    name: gulimall-third-party

server:
  port: 30000
